apiVersion: v1
kind: Service
metadata:
  name: ci-cd-demo
spec:
  type: NodePort
  selector:
    app: ci-cd-demo
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
      nodePort: 30080 # NodePort (range 30000-32767)